name: svg_painter
description: SVG Painter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  change_case: 2.1.0
  path: 1.9.0
  vector_graphics_compiler: 1.1.11+1

flutter:
  uses-material-design: true